### ISSUE TITLE
userId is missing in jwt payload

### ISSUE THREAD

**Issue by whollacsek** [feathersjs/feathers-authentication-oauth1#5]
### Steps to reproduce

Continuation of feathersjs/feathers-authentication-oauth1#4.

- When oauth1 flow is successful the user is redirect to `successRedirect` with the `feathers-jwt` cookie. 
- The `feathers-jwt` cookie contains a `userId` field.
- Client app calls `app.authenticate()` which automatically uses the cookie but returns another jwt which does not contain the `userId`.

The commit feathersjs/feathers-authentication-oauth1@31973709010f55416b2f6469fcdfe55730724f13 doesn't seem to fixe this.

### Expected behavior
On client side when calling `app.authenticate()` should return a jwt with `userId`.

### Actual behavior
A jwt without `userId` is returned.

### System configuration

**Module versions** server:

    "express-session": "^1.14.2",
    "feathers": "^2.0.3",
    "feathers-authentication": "^1.0.2",
    "feathers-authentication-oauth1": "^0.2.3",
    "passport": "^0.3.2",
    "passport-twitter": "^1.0.4",

**Module versions** web:

    "feathers-authentication-client": "^0.1.6",
    "feathers-client": "^1.8.0",

**Comment by whollacsek** [comment]
Found a workaround, don't know if it's the right way.

I had to add 
```js
const jwt = require('feathers-authentication-jwt')
app.configure(jwt())
app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(['twitter']),
      ]
    }
  })
```

The full authentication service is:
```js

const authentication = require('feathers-authentication')
const jwt = require('feathers-authentication-jwt')
const oauth1 = require('feathers-authentication-oauth1')
const session = require('express-session')
const TwitterStrategy = require('passport-twitter').Strategy

module.exports = function () {
  const app = this
  app.use(session({secret: 'super secret', resave: true, saveUninitialized: true}))
  app.configure(authentication(app.get('auth')))
  app.configure(jwt())
  app.configure(oauth1({
    name: 'twitter',
    Strategy: TwitterStrategy,
    successRedirect: '/app'
  }))

  // Authenticate the user using the a JWT or
  // twitter strategy and if successful
  // return a new JWT access token.
  app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate(['twitter']),
      ]
    }
  })
}
```

**Comment by daffl** [comment]
That's what @marshallswain and I ran into as well and it can probably also be solved by registering the hook automatically (as discussed in https://github.com/feathersjs/feathers-authentication-local/issues/4).

/cc @ekryski

**Comment by ekryski** [comment]
Yup that's exactly it. I think having the generator add that by default will make this easier.

**Comment by daffl** [comment]
I'm going to put up PRs to do this by default on the weekend and we can discuss further there.
